### ISSUE TITLE
Failed status actor

### ISSUE THREAD

**Issue by noelia-ledesma88** [epctex-support/walmart-scraper#7]
Hello! Thank you in advance for your time on reviewing this issue

This last monday we tried scraping a site and it shows as finished but failed and the output is empty. Almost all of them were empty except for one. 

The run code example for a failed one: CDsELA8qcaBpcKzgf 
The one that was success at the same day: 35GBoKZRuuz2372hl

Hope it helps and we can have them working soon. 

Thank you!

**Comment by tugkan** [comment]
Hey @noelia-ledesma88 !

Thanks for reaching out. Unfortunately, Walmart has an extremely protected website with a lot of pitfalls. Therefore, scraping the retailer is pretty tough and requires the IPs with the highest quality - and takes time. Can you please use Residential Proxy and let us know how your run goes? 

Best.

**Comment by tugkan** [comment]
Hey @noelia-ledesma88 

We just deployed a version to improve the scraping and set location functionalities. Can you please give it another try with the Residential Proxy?

**Comment by noelia-ledesma88** [comment]
Hello @tugkan !
Thank you for the response and the work done! 
I have tried with residential proxies and it worked at first. But then a timeout issue appeared after some results captured
![Captura de pantalla de 2024-10-17 16-34-19](https://github.com/user-attachments/assets/bc2e3128-66cb-47da-bb37-f41872bc6f3f)

Run id: FccBGtFdzsrrfMRyG

**Comment by tugkan** [comment]
Hey @noelia-ledesma88 ! This is happening because you set the timeout value of 240 seconds. It is happening on the run settings and is unrelated to the actor. 

However, the actor is still not performing well. The main reason for that is the setting zipcode. Unfortunately, Walmart applies a limitation on the Store cookies which let the actor crash.

Until we fix this problem, you can remove your `postalCode` and `zipCode` values completely, and continue scraping. I passed this information to the Engineering Team and they will let us know about the problem on the following week.

**Comment by tugkan** [comment]
Setting location is problematic at the current moment, and we will constantly work on the problem. However, if the problem remains, we might need to depreciate the functionality.

Closing the issue for now, but will keep the issue updated if there will be any change.

**Comment by noelia-ledesma88** [comment]
Ok. Thank you and sorry about the late reply. Unfortunately I totally need that functionality as a requirement for the work I'm doing. I will keep an eye on it and how it gets at the end. Thank you for the update

Regards
